#!/bin/bash -l
#SBATCH --time=24:00:00
#SBATCH -p a100-8
#SBATCH --gres=gpu:a100:2
#SBATCH --ntasks=32
#SBATCH --mem=200g
#SBATCH --tmp=200g
#SBATCH --mail-type=ALL
#SBATCH --mail-user=xxx@xxx.com
#SBATCH --output=R-%Result.txt
#SBATCH --error=R-%Error.txt
module load python3
conda activate eeg
python3 model.py --eegnet_kernel_size x --eegnet_f1 x --eegnet_D x --num_heads x
